version: "3"
services:
  web:
    image: catgpt-webclient
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
